#include <mega32.h>
#include <delay.h>
#include <stdio.h>
#include <i2c.h>
#include <ds1307.h>
#include <alcd.h>

// --- Button Definitions ---
#define MODE_BUTTON PINB.0
#define UP_BUTTON   PINB.1
#define DOWN_BUTTON PINB.2

// --- State Definitions for Settings Mode ---
#define STATE_DISPLAY       0
#define STATE_SET_HOUR      1
#define STATE_SET_MINUTE    2
#define STATE_SET_DAY       3
#define STATE_SET_MONTH     4
#define STATE_SET_YEAR      5

// --- Global Variables ---
unsigned char h, m, s;
unsigned char day, month, year;
char t[16];
char d[16];

// State variable for the settings mode
unsigned char state = STATE_DISPLAY;

// Temporary variables for storing new time/date while setting
unsigned char temp_h, temp_m, temp_day, temp_month, temp_year;


void main(void)
{
    // --- Port Initializations (Generated by CodeVisionAVR) ---
    DDRA=(0<<DDA7) | (0<<DDA6) | (0<<DDA5) | (0<<DDA4) | (0<<DDA3) | (0<<DDA2) | (0<<DDA1) | (0<<DDA0);
    PORTA=(0<<PORTA7) | (0<<PORTA6) | (0<<PORTA5) | (0<<PORTA4) | (0<<PORTA3) | (0<<PORTA2) | (0<<PORTA1) | (0<<PORTA0);

    // Port B initialization for buttons
    // Set PB0, PB1, PB2 as inputs
    DDRB &= ~((1<<DDB2) | (1<<DDB1) | (1<<DDB0));
    // Internal pull-up resistors are disabled for external pull-ups.
    PORTB &= ~((1<<PORTB2) | (1<<PORTB1) | (1<<PORTB0));

    DDRC=(0<<DDC7) | (0<<DDC6) | (0<<DDC5) | (0<<DDC4) | (0<<DDC3) | (0<<DDC2) | (0<<DDC1) | (0<<DDC0);
    PORTC=(0<<PORTC7) | (0<<PORTC6) | (0<<PORTC5) | (0<<PORTC4) | (0<<PORTC3) | (0<<PORTC2) | (0<<PORTC1) | (0<<PORTC0);
    DDRD=(1<<DDD7) | (0<<DDD6) | (0<<DDD5) | (0<<DDD4) | (0<<DDD3) | (0<<DDD2) | (0<<DDD1) | (0<<DDD0);
    PORTD=(0<<PORTD7) | (0<<PORTD6) | (0<<PORTD5) | (0<<PORTD4) | (0<<PORTD3) | (0<<PORTD2) | (0<<PORTD1) | (0<<PORTD0);

    // --- Peripheral Initializations (Generated by CodeVisionAVR) ---
    TCCR0=(0<<WGM00) | (0<<COM01) | (0<<COM00) | (0<<WGM01) | (0<<CS02) | (0<<CS01) | (0<<CS00);
    TCNT0=0x00;
    OCR0=0x00;
    TCCR1A=(0<<COM1A1) | (0<<COM1A0) | (0<<COM1B1) | (0<<COM1B0) | (0<<WGM11) | (0<<WGM10);
    TCCR1B=(0<<ICNC1) | (0<<ICES1) | (0<<WGM13) | (0<<WGM12) | (0<<CS12) | (0<<CS11) | (0<<CS10);
    ASSR=0<<AS2;
    TCCR2=(0<<PWM2) | (0<<COM21) | (0<<COM20) | (0<<CTC2) | (0<<CS22) | (0<<CS21) | (0<<CS20);
    TIMSK=(0<<OCIE2) | (0<<TOIE2) | (0<<TICIE1) | (0<<OCIE1A) | (0<<OCIE1B) | (0<<TOIE1) | (0<<OCIE0) | (0<<TOIE0);
    MCUCR=(0<<ISC11) | (0<<ISC10) | (0<<ISC01) | (0<<ISC00);
    MCUCSR=(0<<ISC2);
    UCSRB=(0<<RXCIE) | (0<<TXCIE) | (0<<UDRIE) | (0<<RXEN) | (0<<TXEN) | (0<<UCSZ2) | (0<<RXB8) | (0<<TXB8);
    ACSR=(1<<ACD) | (0<<ACBG) | (0<<ACO) | (0<<ACI) | (0<<ACIE) | (0<<ACIC) | (0<<ACIS1) | (0<<ACIS0);
    SFIOR=(0<<ACME);

    i2c_init();
    rtc_init(0,1,0);
    lcd_init(16);

    while (1)
    {
        switch(state)
        {
            //NORMAL DISPLAY MODE
            case STATE_DISPLAY:
                rtc_get_time(&h, &m, &s);
                sprintf(t, "%02d:%02d:%02d", h, m, s);
                lcd_gotoxy(4, 0);
                lcd_puts(t);

                rtc_get_date(NULL, &day, &month, &year);
                sprintf(d, "%02d/%02d/20%02d", day, month, year);
                lcd_gotoxy(3, 1);
                lcd_puts(d);

                // Check if MODE button is pressed to enter settings
                if (MODE_BUTTON == 0) {
                    delay_ms(50);
                    while(MODE_BUTTON == 0);
                    rtc_get_time(&temp_h, &temp_m, &s);
                    rtc_get_date(NULL, &temp_day, &temp_month, &temp_year);
                    state = STATE_SET_HOUR; // Go to first setting state
                    lcd_clear();
                }
                break;

            // SETTINGS MODES
            case STATE_SET_HOUR:
                lcd_gotoxy(0,0);
                lcd_puts("Set Hour:       ");

                // --- Button Logic ---
                if (UP_BUTTON == 0)   { delay_ms(50); while(UP_BUTTON == 0); if(++temp_h > 23) temp_h = 0; }
                if (DOWN_BUTTON == 0) { delay_ms(50); while(DOWN_BUTTON == 0); if(temp_h-- == 0) temp_h = 23; }
                if (MODE_BUTTON == 0) { delay_ms(50); while(MODE_BUTTON == 0); state = STATE_SET_MINUTE; lcd_clear(); continue; }

                // Blinking effect for the value being set
                lcd_gotoxy(10,0);
                sprintf(t,"%02d", temp_h);
                lcd_puts(t);
                delay_ms(200);
                lcd_gotoxy(10,0);
                lcd_puts("  ");
                delay_ms(200);
                break;

            case STATE_SET_MINUTE:
                lcd_gotoxy(0,0);
                lcd_puts("Set Minute:     ");

                if (UP_BUTTON == 0)   { delay_ms(50); while(UP_BUTTON == 0); if(++temp_m > 59) temp_m = 0; }
                if (DOWN_BUTTON == 0) { delay_ms(50); while(DOWN_BUTTON == 0); if(temp_m-- == 0) temp_m = 59; }
                if (MODE_BUTTON == 0) { delay_ms(50); while(MODE_BUTTON == 0); state = STATE_SET_DAY; lcd_clear(); continue; }

                lcd_gotoxy(12,0);
                sprintf(t,"%02d", temp_m);
                lcd_puts(t);
                delay_ms(200);
                lcd_gotoxy(12,0);
                lcd_puts("  ");
                delay_ms(200);
                break;

            case STATE_SET_DAY:
                lcd_gotoxy(0,0);
                lcd_puts("Set Day:        ");

                if (UP_BUTTON == 0)   { delay_ms(50); while(UP_BUTTON == 0); if(++temp_day > 31) temp_day = 1; }
                if (DOWN_BUTTON == 0) { delay_ms(50); while(DOWN_BUTTON == 0); if(temp_day-- < 2) temp_day = 31; }
                if (MODE_BUTTON == 0) { delay_ms(50); while(MODE_BUTTON == 0); state = STATE_SET_MONTH; lcd_clear(); continue; }

                lcd_gotoxy(9,0);
                sprintf(t,"%02d", temp_day);
                lcd_puts(t);
                delay_ms(200);
                lcd_gotoxy(9,0);
                lcd_puts("  ");
                delay_ms(200);
                break;

            case STATE_SET_MONTH:
                lcd_gotoxy(0,0);
                lcd_puts("Set Month:      ");

                if (UP_BUTTON == 0)   { delay_ms(50); while(UP_BUTTON == 0); if(++temp_month > 12) temp_month = 1; }
                if (DOWN_BUTTON == 0) { delay_ms(50); while(DOWN_BUTTON == 0); if(temp_month-- < 2) temp_month = 12; }
                if (MODE_BUTTON == 0) { delay_ms(50); while(MODE_BUTTON == 0); state = STATE_SET_YEAR; lcd_clear(); continue; }

                lcd_gotoxy(11,0);
                sprintf(t,"%02d", temp_month);
                lcd_puts(t);
                delay_ms(200);
                lcd_gotoxy(11,0);
                lcd_puts("  ");
                delay_ms(200);
                break;

            case STATE_SET_YEAR:
                lcd_gotoxy(0,0);
                lcd_puts("Set Year: 20    ");

                if (UP_BUTTON == 0)   { delay_ms(50); while(UP_BUTTON == 0); if(++temp_year > 99) temp_year = 0; }
                if (DOWN_BUTTON == 0) { delay_ms(50); while(DOWN_BUTTON == 0); if(temp_year-- == 0) temp_year = 99; }
                // Last setting: MODE button saves and exits
                if (MODE_BUTTON == 0) {
                    delay_ms(50);
                    while(MODE_BUTTON == 0);
                    // Write all temporary values to the RTC
                    rtc_set_time(temp_h, temp_m, 0);
                    rtc_set_date(1, temp_day, temp_month, temp_year);
                    state = STATE_DISPLAY;
                    lcd_clear();
                    continue;
                }

                lcd_gotoxy(12,0);
                sprintf(t,"%02d", temp_year);
                lcd_puts(t);
                delay_ms(200);
                lcd_gotoxy(12,0);
                lcd_puts("  ");
                delay_ms(200);
                break;
        }
    }
}





